### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by DoubleDBE** [horse-framework/horse-messaging#149]
This looks like a very cool library to look into!

However, where are the docs, if any?

Google doesn't help me very much.

**Comment by mhelvacikoylu** [comment]
Hello,

We had a good documentation for previous versions but we changed a lot and removed old docs.
Now working on a new documentation for latest (version 6) version.

**Comment by DoubleDBE** [comment]
Okay great!

Awaiting the docs, i'll just ask my question: 

Can this library be used for creating a "clustered network" on the LAN and replicate POCO objects over TCP to multiple devices / nodes?

**Comment by mhelvacikoylu** [comment]
Yes. It's possible.
Your applications (the clients that are connected to your horse messaging server) can communicate each other different ways; sending message, request-response, over caches, over channel streams or over queues. persistence in server side depends to you (horse supports binary file persistance) you can keep messages whatever you want such as sql server etc. and server can work on multiple nodes with two-kind of clustering options. For further information you can check the documentation when it's ready.

**Comment by DoubleDBE** [comment]
Is it also possible to have each device in the network to be a server AND a client at the same time?
Without having the need for a centralised server.

What I mean by that is this:

Let's say I have 4 devices, A, B, C and D, each one running a SqLite database.

Device A creates a POCO object and sends it to B, C and D, each device persist this object in their own SqLite database.

Device C creates a POCO object and sends it to A, B and D, each device persist this object in their own SqLite database.

Then, let's say device B crashes.
While device B has crashed, device A, C and D are still sending POCO objects to each other.

When device B comes back online, is it possible to ask this question to the other devices?:
"Give me all the new data you were sending to each other so I can persist this in my own database and be up to date with all the new data"

My apologies for the questions! If you have a preview of the docs, please provide me a link so I can try this on my own!

**Comment by DoubleDBE** [comment]
Hello,

Is there SOME (preview) documentation available please?

I've been fiddling around for more than a week now, and i'm getting somewhere but i'm missing a lot of pieces.

This project seems like a perfect candidate for usage in our application and it would be a shame to end up not using it.

It doesn't have to be a fully fledged guide, but some essential basics would suffice.

Thanks

**Comment by hizliemre** [comment]
You can check the sample projects in the repo. What are your expectations?

**Comment by DoubleDBE** [comment]
Yeah, I checked the samples. But they're not really explanatory on **what** they're doing, and _why_.

I even cloned the whole repo and tried some things I could find from the unit tests.

And even after all that I'm still scratching my head on why some things aren't working.
(eg sending a message from the server to all clients).

Like, when, _why_ and _how_ should I use `Direct` messaging?
When, _why_ and _how_ should I use `Channels`?
When, _why_ and _how_ should I use `Routers`?
etc ...

I know it al depends on the requirements, but that's the whole point.

Due to the lacking docs i'm having a hard time figuring out what would be best for my use case.

What's the status of the docs?
